ALTER TABLE "IntentPolicyConfig"
  ADD COLUMN IF NOT EXISTS "signalWeights" JSONB,
  ADD COLUMN IF NOT EXISTS "domainClasses" JSONB,
  ADD COLUMN IF NOT EXISTS "normalizationRules" JSONB,
  ADD COLUMN IF NOT EXISTS "toolScopeMappings" JSONB,
  ADD COLUMN IF NOT EXISTS "taskDefaults" JSONB,
  ADD COLUMN IF NOT EXISTS "alignmentReliefEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "alignmentReliefThreshold" INTEGER NOT NULL DEFAULT 85;

ALTER TABLE "ExecutionIntent"
  ADD COLUMN IF NOT EXISTS "baselinePatched" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "baselineVersion" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "baselinePatchedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "baselinePatchedBy" TEXT,
  ADD COLUMN IF NOT EXISTS "baselinePatchReason" TEXT;
